#!/usr/bin/env bash
# PreToolUse guard (Edit|Write|NotebookEdit) for the implementer subagent:
# refuses edits to the root AGENTS.md "Do not touch" paths, the agent/hook
# config, the plan itself, INSIGHTS.md and the lint:arch baseline.
# Exit 2 + stderr = block.
set -euo pipefail

payload="$(cat)"
file="$(printf '%s' "$payload" | jq -r '.tool_input.file_path // .tool_input.notebook_path // ""')"
[[ -n "$file" ]] || exit 0

root="$(realpath -m -- "${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}")"
# Normalise so `server/x/../src/db/migrations/…` cannot slip past the patterns.
[[ "$file" == /* ]] || file="$root/$file"
abs="$(realpath -m -- "$file")"
rel="${abs#"$root"/}"
[[ "$rel" != "$abs" ]] || rel="$abs"

deny() {
  echo "implementer: blocked edit of '$rel' — $1. Stop and report it under 'Not done / blockers' instead of working around it." >&2
  exit 2
}

# The plan may opt into design-system work with the line "Design-system task: yes".
branch="$(git -C "$root" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")"
plan="$root/docs/plans/${branch//\//-}.md"
design_ok=0
[[ -f "$plan" ]] && grep -qi '^[-* ]*design-system task:[[:space:]]*yes' "$plan" && design_ok=1

case "$rel" in
  /*) deny "path is outside the repository" ;;
  */pnpm-lock.yaml | pnpm-lock.yaml | */package-lock.json | package-lock.json | skills-lock.json)
    deny "lockfiles are written only by the package manager" ;;
  .claude/*) deny "agent, hook, skill and settings files are not the implementer's to change" ;;
  client/src/vendor/shared/*)
    deny "the client contract copy is never edited; change server/src/vendor/shared and copy it with cp" ;;
  client/src/vendor/ui/*)
    [[ $design_ok == 1 ]] || deny "design system; allowed only when the plan says 'Design-system task: yes'" ;;
  server/src/db/migrations/*) deny "migrations are generated by 'pnpm db:generate' from src/db/schema" ;;
  server/.dependency-cruiser-known-violations.json) deny "the lint:arch baseline is never grown by hand" ;;
  */INSIGHTS.md | INSIGHTS.md) deny "INSIGHTS.md is written only through insight.sh add" ;;
  docs/plans/*) deny "the plan is owned by the planner and the main session" ;;
  .env* | */.env*) deny "env files hold machine-specific values and secrets" ;;
  server/clones/* | e2e/test-results/* | */node_modules/* | node_modules/* | */.next/* | */dist/*)
    deny "runtime or generated output" ;;
esac

exit 0
