import type { CSSProperties } from "react";

export const s = {
  headRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  label: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  quote: {
    fontSize: 16,
    fontStyle: "italic",
    lineHeight: 1.5,
    color: "var(--text-primary)",
    margin: "14px 0 0",
  } satisfies CSSProperties,
  scopeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 16,
    marginTop: 16,
  } satisfies CSSProperties,
  scopeTitle: (color: string): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color,
    marginBottom: 6,
  }),
  list: { margin: 0, padding: 0, listStyle: "none", fontSize: 13, lineHeight: 1.7, color: "var(--text-secondary)" } satisfies CSSProperties,
  bullet: { color: "var(--text-muted)", marginRight: 6 } satisfies CSSProperties,
  disclosure: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    marginTop: 16,
    paddingTop: 12,
    border: "none",
    borderTop: "1px solid var(--border)",
    background: "transparent",
    fontSize: 12,
    color: "var(--text-muted)",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  sources: { display: "flex", flexDirection: "column", gap: 6, margin: "10px 0 0", padding: 0 } satisfies CSSProperties,
  sourceRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
    flexWrap: "wrap",
    listStyle: "none",
  } satisfies CSSProperties,
  sourceKind: { color: "var(--text-muted)", minWidth: 96 } satisfies CSSProperties,
  sourceRef: { color: "var(--text-primary)", wordBreak: "break-all" } satisfies CSSProperties,
  reason: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  derived: { marginTop: 10, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  centered: { display: "flex", justifyContent: "center" } satisfies CSSProperties,
} as const;
