import type { CSSProperties } from "react";

/** Styles for the inline finding comment (CSS variables only). */
export const fs = {
  wrap: (sevColor: string, muted: boolean): CSSProperties => ({
    margin: "6px 14px 8px 58px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderWidth: 1,
    borderLeftWidth: 3,
    borderLeftColor: sevColor,
    borderRadius: 8,
    background: "var(--bg-elevated)",
    opacity: muted ? 0.65 : 1,
    fontFamily: "inherit",
  }),
  head: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px 0",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  title: (dismissed: boolean): CSSProperties => ({
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
    textDecoration: dismissed ? "line-through" : "none",
  }),
  grow: { flex: 1 } satisfies CSSProperties,
  meta: { fontSize: 12, color: "var(--text-muted)", padding: "4px 12px 0" } satisfies CSSProperties,
  body: { padding: "8px 12px 12px" } satisfies CSSProperties,
  prose: { fontSize: 13, lineHeight: 1.55, color: "var(--text-secondary)" } satisfies CSSProperties,
  fixBox: {
    marginTop: 10,
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  fixLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  actions: { display: "flex", gap: 8, marginTop: 10 } satisfies CSSProperties,
  acceptedTag: { fontSize: 12, fontWeight: 600, color: "var(--ok)" } satisfies CSSProperties,
  dismissedTag: { fontSize: 12, fontWeight: 600, color: "var(--text-muted)" } satisfies CSSProperties,
  collapsedRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "6px 12px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    color: "var(--text-primary)",
    font: "inherit",
  } satisfies CSSProperties,
} as const;
